name: Deploy to dev env
on:
  push:
env:
  PROJECT_FOLDER: /var/www/timetable/backend
  TEST_TAG: dzhuryn/timetable-backend-php:test
jobs:
  test:
    name: Code lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          docker-user: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/php/Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Check code style
        run: |
          docker run --rm ${{ env.TEST_TAG }} composer run cs-check
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          docker-user: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build php and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/php/Dockerfile
          tags: dzhuryn/timetable-backend-php:dev
      - name: Build webserver and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/nginx/Dockerfile
          tags: dzhuryn/timetable-backend-webserver:dev
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ssh key passphrase
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          debug: true
          script: |
            cd ${{ env.PROJECT_FOLDER }}
            docker-compose pull
            docker-compose up -d
            docker-compose exec php php artisan migrate
